workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Clean and build IPA
        script: |
          flutter clean
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - xaranex@gmail.com  # Replace with your email for notifications
