name: iOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x'
        channel: 'stable'

    - name: Get dependencies
      run: flutter pub get

    - name: Build iOS
      run: flutter build ipa --release

    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: appkatest-ios-ipa
        path: build/ios/ipa/*.ipa
