   name: iOS Build

   on:
     push:
       branches: [ main ]
     pull_request:
       branches: [ main ]

   jobs:
     build-ios:
       runs-on: macos-latest

       steps:
       - uses: actions/checkout@v4

       - name: Install Flutter
         uses: subosito/flutter-action@v2
         with:
           flutter-version: '3.x'
           channel: 'stable'

       - name: Get Flutter dependencies
         run: flutter pub get

       - name: Generate iOS platform files if missing
         run: flutter create --platforms=ios .

       - name: Install iOS dependencies (CocoaPods)
         run: |
           cd ios
           pod install --repo-update

       - name: Build iOS IPA
         run: flutter build ipa --release --no-codesign

       - name: Upload IPA artifact
         uses: actions/upload-artifact@v4
         with:
           name: appkatest-ios-ipa
           path: build/ios/ipa/*.ipa
